dotnet-core-buildpack/dotnet-core_buildpack-cflinuxfs4-v2.4.47.zip:
  size: 6272795
  object_id: 38e78400-44fe-40e5-4fd4-5f030e47d867
  sha: sha256:fa6717b41eb0a7807264275a3957803164e4150fec5b227405c30fd0219ebd3a
