dotnet-core-buildpack/dotnet-core_buildpack-cflinuxfs4-v2.4.46.zip:
  size: 6272203
  object_id: ee6f57b3-880a-4e25-6379-3f0fe19194da
  sha: sha256:f83addf2272528d5a2cc2e74d5363ce36714d23803d889dd6a743f4bf5bcf192
